######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 24 15:04:35 2020
######################################################################
QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h tetrahedron.h window.h
SOURCES += globj.cpp tetrahedron.cpp window.cpp
